# Problem 4-55

In [1]:
import numpy as np

m = 5
n = 10000

h = np.array([1,2,3,4,5])
hh = np.zeros(m)
f = np.random.randn(n)
fn = np.hstack(([0,0,0,0],f))
delta = .0001
P = 1/delta * np.eye(m)
q = np.zeros(m)

for i in range(n):
    d = fn[i:i+5] @ h
    q = np.hstack((f[i],q[:-1]))

    k = P @ q / (1 + q.T @ P @ q)
    e = d - q @ hh

    hh = hh + k * e
    P = P - k * q @ P

print('hh=\n',hh)

hh=
 [5. 4. 3. 2. 1.]


### With only 3 parameters:

In [10]:
m = 3
n = 10000

h = np.array([1,2,3,4,5])
hh = np.zeros(m)
f = np.random.randn(n)
fn = np.hstack(([0,0,0,0],f))
delta = .0001
P = 1/delta * np.eye(m)
q = np.zeros(m)

for i in range(n):
    d = fn[i:i+5] @ h
    q = np.hstack((f[i],q[:-1]))

    k = P @ q / (1 + q.T @ P @ q)
    e = d - q @ hh

    hh = hh + k * e
    P = P - k * q @ P

print('hh=\n',hh)

hh=
 [14.35694009 35.0646881  14.96112589]


# Problem 5-2

In [3]:
def solve_lu(L, U, b):
    c = b
    m = c.size
    x = np.zeros(m)
    y = np.zeros(m)

    # Forward substitution
    for j in range(m):
        y[j] = c[j] - L[j,:][:j] @ y[:j]

    # Back substitution
    for j in range(m-1,-1,-1):
        x[j] = ( 1/U[j][j] )*( y[j] - U[j,:][j+1:] @ x[j+1:] )

    return x


L = np.array([[1,0],[2,1]])
U = np.array([[3,4],
              [0,5]])
b = np.array([6,7])

x = solve_lu(L,U,b)

print('x =', x)

x = [ 3.33333333 -1.        ]


# Problem 5-4

In [4]:
from math import log10, floor
from scipy import linalg as la

np.set_printoptions(suppress=True)

def round_sig(x, sig=3):
    if x.size == 1 and x==0:
        return x
    elif type(x) != np.ndarray:
        x = round(x, sig-int(floor(log10(abs(x))))-1)
    else:
        for i in range(x.size):
            x[i] = round(x[i], sig-int(floor(log10(abs(x[i]))))-1)

    return x

def solve_lu(A, b):
    c = b
    m = A.shape[0]
    x = np.zeros(m)
    y = np.zeros(m)
    E = np.array([np.eye(m)]*(m-1))
    E_inv = np.copy(E)
    U = np.copy(A)
    L = np.eye(m)

    # LU decomposition
    for j in range(m-1): # loop through cols of A
        vals = - round_sig(U[j+1:m,j] / U[j,j])
        E[j,j+1:m,j] = vals
        E_inv[j,j+1:m,j] = -vals

        U = E[j] @ U
        L = L @ E_inv[j]

    print('U=\n',U)
    print('L=\n',L)

    # Forward substitution
    for j in range(m):
        y[j] = round_sig(c[j] - L[j,:][:j] @ y[:j])

    # Back substitution
    for j in range(m-1,-1,-1):
        x[j] = ( 1/U[j,j] )*( y[j] - U[j,:][j+1:] @ x[j+1:] )

    return x

A = np.array([[2,4,-5],
              [6,12.001,1],
              [4,-8,-3]])

b = np.array([-5,33.002,-21])

x = solve_lu(A,b)

print('x=',x)

U=
 [[     2.         4.        -5.   ]
 [     0.         0.001     16.   ]
 [     0.        -0.    256007.   ]]
L=
 [[     1.      0.      0.]
 [     3.      1.      0.]
 [     2. -16000.      1.]]
x= [2.3748667  1.31246411 2.99991797]


### Using pivoting:

In [5]:
def solve_lu_pivot(A, b):
    P, L, U = la.lu(A)

    c = P.T@b
    m = A.shape[0]
    x = np.zeros(m)
    y = np.zeros(m)

    print('U=\n',U)
    print('L=\n',L)

    # Forward substitution
    for j in range(m):
        y[j] = round_sig(c[j] - L[j,:][:j] @ y[:j])

    # Back substitution
    for j in range(m-1,-1,-1):
        x[j] = ( 1/U[j,j] )*( y[j] - U[j,:][j+1:] @ x[j+1:] )

    return x

x_pivot = solve_lu_pivot(A,b)

print('x_pivot=',x_pivot)

U=
 [[  6.          12.001        1.        ]
 [  0.         -16.00066667  -3.66666667]
 [  0.           0.          -5.33325695]]
L=
 [[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.00002083 1.        ]]
x_pivot= [0.99984587 1.99990682 3.00004297]


 # Problem 5-5

In [6]:
A = np.array([[4,6,4],[6,25,18],[4,18,22]])

L = np.linalg.cholesky(A)
m = L.shape[0]
U = np.eye(m)
D = np.eye(m)

for i in range(m):
    U[i+1:m,i] = L[i+1:m,i] / L[i,i]
    D[i,i] = L[i,i]**2

U = U.T

print('L=\n',L)
print('U=\n',U)
print('D=\n',D)


L=
 [[2. 0. 0.]
 [3. 4. 0.]
 [2. 3. 3.]]
U=
 [[1.   1.5  1.  ]
 [0.   1.   0.75]
 [0.   0.   1.  ]]
D=
 [[ 4.  0.  0.]
 [ 0. 16.  0.]
 [ 0.  0.  9.]]
